#!/bin/bash

# Lista de URLs a escanear
urls=(

     "https://formaciowp.host3ip.eu/.git"


)

# Iterar sobre cada URL en la lista
for url in "${urls[@]}"
do
    echo "Escaneando $url ..."
    dirb "$url" "diccionario_workplace.txt"   # Ejecutar Dirb para la URL actual
    echo "------------------------------"
done
